// API Types aligned with backend Pydantic schemas

// ── Auth Types ───────────────────────────────────────────────────────────

export interface UserRegister {
  name: string
  email: string
  phone?: string
  password: string
  role?: string
}

export interface UserLogin {
  email: string
  password: string
}

export interface UserResponse {
  id: string
  name: string
  email: string
  phone?: string
  role: string
  is_active: boolean
  created_at: string
}

export interface TokenResponse {
  access_token: string
  token_type: string
  user?: UserResponse
}

// ── Store Types ──────────────────────────────────────────────────────────

export interface Store {
  id: string
  owner_id: string
  name: string
  location?: string
  phone?: string
  email?: string
  timezone: string
  currency: string
  tax_inclusive: boolean
  chain_id?: string
  state?: string
  city?: string
  outlet_type?: string
  table_count: number
  is_active: boolean
  created_at: string
}

export interface StoreCreate {
  name: string
  location?: string
  phone?: string
  email?: string
  timezone?: string
  currency?: string
  tax_inclusive?: boolean
  chain_id?: string
  state?: string
  city?: string
  outlet_type?: string
  table_count?: number
}

export interface StoreUpdate extends Partial<StoreCreate> {
  is_active?: boolean
}

// ── Table Types (dynamic labels from table_count) ────────────────────────

export interface TableLabel {
  table_number: number
  table_label: string
}

export interface StoreTablesResponse {
  store_id: string
  table_count: number
  tables: TableLabel[]
}

// For backward compatibility in components that need Table-like objects
export interface Table {
  id: string
  store_id: string
  label: string
  capacity: number
  status: 'available' | 'occupied' | 'reserved'
}

// ── Employee Types ───────────────────────────────────────────────────────

export interface Employee {
  id: string
  store_id: string
  user_id?: string
  name: string
  employee_code: string
  phone?: string
  email?: string
  role: string
  is_active: boolean
  permissions?: Record<string, unknown> | null
  created_at: string
}

export interface EmployeeCreate {
  store_id: string
  name: string
  employee_code?: string  // Optional — auto-generated by backend
  pin: string
  phone?: string
  email?: string
  role?: string
  user_id?: string
  permissions?: string[]
}

export interface EmployeeUpdate {
  name?: string
  pin?: string
  phone?: string
  email?: string
  role?: string
  is_active?: boolean
  permissions?: string[]
}

// ── Permission Groups ────────────────────────────────────────────────────

export interface PermissionGroup {
  id: string
  name: string
  permissions: string[]
  created_at: string
}

// ── Menu / Product Types (aligned with backend /products routes) ─────────

export interface Category {
  id: string
  store_id: string
  name: string
}

export interface CategoryCreate {
  name: string
}

export interface CategoryUpdate {
  name?: string
}

export interface MenuItem {
  id: string
  store_id: string
  category_id: string
  name: string
  description?: string
  price: number
  tax_percent: number
  is_active: boolean
}

export interface MenuItemCreate {
  category_id: string
  name: string
  description?: string
  price: number
  tax_percent?: number
  is_active?: boolean
}

export interface MenuItemUpdate {
  category_id?: string
  name?: string
  description?: string
  price?: number
  tax_percent?: number
  is_active?: boolean
}

export interface AddOn {
  id: string
  name: string
  price: number
}

// ── Order Types ──────────────────────────────────────────────────────────

export type OrderStatus = 'pending' | 'confirmed' | 'preparing' | 'ready' | 'served' | 'completed' | 'cancelled'
export type OrderType = 'dine_in' | 'takeaway' | 'delivery'
export type PaymentMethod = 'cash' | 'card' | 'upi' | 'wallet' | 'gift_card'
export type PaymentStatus = 'pending' | 'completed' | 'refunded'

export interface OrderItem {
  id: string
  order_id: string
  product_id?: string
  product_name: string
  quantity: number
  price: number
  tax_amount: number
  discount_amount: number
  total: number
  status: string
  notes?: string
  kitchen_status?: string
  cancel_reason?: string
  // Frontend convenience fields (mapped from backend)
  menu_item_id?: string
  menu_item_name?: string
  unit_price?: number
  subtotal?: number
  add_ons?: OrderItemAddOn[]
}

export interface OrderItemAddOn {
  name: string
  price: number
}

export interface Order {
  id: string
  store_id: string
  employee_id?: string
  terminal_id?: string
  table_number?: number
  guest_id?: string
  shift_id?: string
  order_number?: string
  order_type: string
  status: OrderStatus
  channel?: string
  gross_amount: number
  tax_amount: number
  discount_amount: number
  service_charge: number
  tip_amount: number
  net_amount: number
  payment_status: string
  notes?: string
  cancel_reason?: string
  device_id?: string
  sync_status?: string
  created_at: string
  updated_at?: string
  items: OrderItem[]
  // Convenience aliases for UI (computed from backend fields)
  table_label?: string
  customer_name?: string
  customer_phone?: string
  subtotal?: number
  tax?: number
  discount?: number
  total?: number
  progress?: number
}

export interface OrderCreate {
  store_id: string
  employee_id?: string
  terminal_id?: string
  table_number?: number
  guest_id?: string
  shift_id?: string
  order_type: string
  channel?: string
  discount_amount?: number
  service_charge?: number
  notes?: string
  items: {
    product_id: string
    quantity: number
    price: number
    notes?: string
  }[]
}

// ── Payment Types ────────────────────────────────────────────────────────

export interface Payment {
  id: string
  order_id: string
  payment_method: string
  amount: number
  tip_amount: number
  reference?: string
  is_refund: boolean
  paid_at: string
  device_id?: string
  sync_status?: string
  // Convenience aliases for UI
  method?: string
  status?: string
  created_at?: string
}

// ── KOT (Kitchen Order Ticket) ───────────────────────────────────────────

export interface KOT {
  id: string
  order_id: string
  store_id: string
  items: KOTItem[]
  status: 'pending' | 'preparing' | 'ready'
  created_at: string
  printed_at?: string
}

export interface KOTItem {
  menu_item_name: string
  quantity: number
  notes?: string
}

// ── Inventory ────────────────────────────────────────────────────────────

export interface InventoryItem {
  id: string
  store_id: string
  name: string
  sku: string
  quantity: number
  unit: string
  min_stock_level: number
  is_low_stock: boolean
  last_updated: string
}

// ── Order Timeline Event ─────────────────────────────────────────────────

export interface OrderTimelineEvent {
  id: string
  order_id: string
  event_type: 'pending' | 'created' | 'confirmed' | 'preparing' | 'ready' | 'served' | 'completed' | 'cancelled' | 'payment_received'
  description: string
  created_at: string
  created_by?: string
}

// ── Analytics Types ──────────────────────────────────────────────────────

export interface AnalyticsSummary {
  total_revenue: number
  total_orders: number
  tax_collected: number
  gross_sales: number
  net_sales: number
  total_discounts: number
  payment_breakdown: Record<string, number>
}

export interface OutletStat {
  store_id: string
  store_name: string
  total_revenue: number
  total_orders: number
  tax_collected: number
  gross_sales: number
  net_sales: number
  total_discounts: number
  payment_breakdown: Record<string, number>
}

export interface OutletAnalyticsResponse {
  outlets: OutletStat[]
  totals: AnalyticsSummary
}

// ── Shift Types ──────────────────────────────────────────────────────────

export interface Shift {
  id: string
  store_id: string
  employee_id: string
  terminal_id?: string
  status: 'open' | 'closed'
  started_at: string
  ended_at?: string
  opening_cash?: number
  closing_cash?: number
  notes?: string
  payment_summaries?: ShiftPaymentSummary[]
}

export interface ShiftPaymentSummary {
  payment_method: string
  total_amount: number
  transaction_count: number
}

export interface DayClose {
  id: string
  store_id: string
  business_date: string
  closed_by: string
  total_revenue: number
  total_orders: number
  total_cash: number
  total_card: number
  total_upi: number
  total_expenses: number
  net_cash: number
  created_at: string
}

// ── Report Types ─────────────────────────────────────────────────────────

export interface ReportTemplate {
  id: string
  code: string
  name: string
  description?: string
  category: string
  parameters_schema?: Record<string, unknown>
  is_active: boolean
  created_at: string
}

export interface ReportRun {
  id: string
  template_id: string
  store_id: string
  requested_by: string
  parameters?: Record<string, unknown>
  status: string
  result?: Record<string, unknown>
  error?: string
  created_at: string
  completed_at?: string
}

// ── Notification Types ───────────────────────────────────────────────────

export interface Notification {
  id: string
  user_id: string
  store_id?: string
  title: string
  body: string
  category?: string
  is_read: boolean
  created_at: string
}

// ── Expense Types ────────────────────────────────────────────────────────

export interface Expense {
  id: string
  store_id: string
  title: string
  amount: number
  category?: string
  notes?: string
  shift_id?: string
  created_at: string
}

export interface ExpenseCreate {
  store_id: string
  title: string
  amount: number
  category?: string
  notes?: string
  shift_id?: string
}

// ── Menu Schedule ────────────────────────────────────────────────────────

export interface MenuSchedule {
  id: string
  menu_id: string
  day_of_week: number
  start_time: string
  end_time: string
}

// ── API Response wrapper ─────────────────────────────────────────────────

export interface ApiResponse<T> {
  data: T
  message?: string
}

export interface PaginatedResponse<T> {
  items: T[]
  total: number
  page: number
  page_size: number
  pages: number
}
